# SPDX-FileCopyrightText: 2026 Demerzel Solutions Limited
# SPDX-License-Identifier: MIT

file(WRITE "${OUTPUT}" "Licenses from the Linux native dependency build, including Folly.\nGenerated from the pinned vcpkg build.\n")
file(GLOB licenses "${DEPS}/share/*/copyright")
list(SORT licenses)
foreach(license IN LISTS licenses)
  get_filename_component(directory "${license}" DIRECTORY)
  get_filename_component(port "${directory}" NAME)
  file(SHA256 "${license}" hash)
  file(READ "${license}" text)
  list(APPEND hashes "${hash}")
  list(APPEND ports_${hash} "${port}")
  set(text_${hash} "${text}")
endforeach()
list(REMOVE_DUPLICATES hashes)
foreach(hash IN LISTS hashes)
  list(JOIN ports_${hash} ", " ports)
  file(APPEND "${OUTPUT}" "\n\n${ports}\n========================================\n${text_${hash}}\n")
endforeach()
