<Project>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <UseArtifactsOutput>true</UseArtifactsOutput>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <PropertyGroup Label="ProductInfo">
    <Authors>Nethermind</Authors>
    <Copyright>Demerzel Solutions Limited</Copyright>
    <VersionPrefix>11.8.1</VersionPrefix>
    <VersionSuffix>preview</VersionSuffix>
  </PropertyGroup>

</Project>
